Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,14 +53,17 @@ jobs:
       - name: List contents of the root directory after checkout
         run: |
           echo "Listing contents of the current directory after checkout"
-          pwd
           ls -alh
 
       - name: List contents of flask-app directory (if exists)
         run: |
-          echo "Listing contents of /home/runner/work/flask-app/flask-app directory"
-          
-          ls -alh 
+          echo "Listing contents of flask-app directory"
+          if [ -d "flask-app" ]; then
+            ls -alh flask-app
+          else
+            echo "flask-app directory not found."
+            exit 1
+          fi
 
   build:
     runs-on: ubuntu-latest
@@ -138,5 +141,6 @@ jobs:
           else
             echo "No changes to commit."
           fi
+
 
 
